kiwmi_output:usable_area() and :on("usable_area_change")
buffet/kiwmi pull request #32
Opened 2021-08-11 18:52 UTC by tiosgz

This is especially useful for window tiling and maximizing.

(another PR from `tiosgz/mine`, commits f378b29a61fc960711ab69b54d1d7d3bbc76a782 and b0569ea72bb5482dd760c66eae866d2b8844a621)

2021-08-11 20:11 UTC, buffet requested changes
Thanks! I was actually just discussing this with a friend!

Could you run clang-format (`clang-format -i **/*.{c,h}`) over the project please?

2021-08-11 20:11 UTC, buffet commented on kiwmi/desktop/layer_shell.c
> +                sizeof(struct wlr_box)) != 0) {
Prefer sizeof(usable_area).

2021-08-11 20:31 UTC, tiosgz commented on kiwmi/desktop/layer_shell.c
> +                sizeof(struct wlr_box)) != 0) {
Sure; done.

2021-08-12 08:45 UTC, buffet approved these changes
Thanks!

2021-08-12 08:45 UTC, merged